// <auto-generated />
namespace Blogging_Assignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MyBloggingAssignmentDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MyBloggingAssignmentDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202103031530382_MyBloggingAssignmentDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
